---
- name: Install Docker
  when: ansible_distribution == "Debian"
  apt: name="{{ item }}" update_cache=yes state=latest
  loop:
  - docker
  - docker.io
  - docker-compose
  - docker-registry
  - pip
  - nmap


- name: Install Python et pip
  when: ansible_distribution == "Debian"
  apt: name="{{ item }}" update_cache=yes state=latest
  loop:
  - python3
  - pip

- name: Install modules python
  when: ansible_distribution == "Debian"
  pip: name="{{ item }}"
  loop:
  - paramiko
  - python-nmap

#- name: Install Packages Redhat
#  yum: name="{{ item }}" update_cache=yes state=latest
#  loop:
#   - nginx
#   - mariadb-server
#   - php-fpm
#   when: ansible_distribution == "Redhat"
