FROM  python:latest
#Spécifier le répertoire de travail
COPY . /
WORKDIR /


#Installation des dependences
# Installation de pip et nmap 
RUN apt update &&\ 
    apt-get install pip nmap -y
# MAJ de pip
RUN pip install --no-cache-dir --upgrade pip

# Flask
RUN pip3 install flask


ENV PYTHONUNBUFFERED 1

EXPOSE 8082

# PYTHON
# Installation des modules python paramiko et python-nmap
RUN pip3 install paramiko==2.11.0 python-nmap==0.7.1

#Lancement des scripts
RUN python3 scan2.py
RUN python3 paramiko.py
