# ---
# - name: Supprimer l'emplacement du site par defaut
#   file: path=/var/www/html state=absent

# - name: Ajouter le nouvel emplacement
#   file: path=/var/www/my state=directory

# - name: Modification du Vhost apache
#   replace: dest=/etc/apache2/sites-enabled/000-default.conf regexp='/var/www/html' replace='/var/www/my'
#   notify: apache2 reload
#   when: ansible_facts['distribution'] == "Debian"

# - name: Suppression du Vhost nginx
#   file: path=/etc/nginx/sites-enabled/default state=absent
#   when: ansible_facts['os_family'] == "RedHat"

# - name: Creation du nouveau Vhost nginx
#   template: src=templates/vhost.j2 dest=/etc/nginx/sites-enabled/default
#   notify: nginx reload
#   when: ansible_facts['os_family'] == "RedHat"

# - name: Configuration de ma page php
#   template: src=templates/index.j2 dest=/var/www/my/index.php

# - name: Supression fonction php/apache
#   replace: dest=/etc/php/7.4/apache2/php.ini regexp='allow_url_fopen = On' replace='allow_url_fopen = Off'
#   notify: apache2 reload
#   when: ansible_facts['os_family'] == "Debian"
#  - name: Supression fonction php/nginx
#    replace: dest=/etc/php/7.0/fpm/php.ini regexp='allow_url_fopen = On' replace='allow_url_fopen = Off'
#    notify: php-fpm reload
#    when: ansible_distribution == "CentOS"
